/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/brake.glb --transform --js 
Files: public/brake.glb [1.54MB] > /home/mohamed/Desktop/Mohamed/cars_lists/3d advertising/brake/brake-transformed.glb [175.15KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brake-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['13482_Brake_Rotor_v1_L2'].geometry} material={materials.brake_rotor_body} rotation={[Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/brake-transformed.glb')
